# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('mec-sim_scenario1', ['core', 'mobility', 'network', 'mec-sim', 'propagation'])
    obj.source = 'mec-sim_scenario1.cc'

    obj = bld.create_ns3_program('mec-sim_scenario2', ['core', 'mobility', 'network', 'mec-sim', 'propagation'])
    obj.source = 'mec-sim_scenario2.cc'